
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Serverless Fitness Logger Infrastructure'

Resources:
  # DynamoDB Table
  FitnessWorkoutsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FitnessWorkouts
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: workoutId
          AttributeType: S
      KeySchema:
        - AttributeName: workoutId
          KeyType: HASH

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'fitness-logger-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # Bucket Policy
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${FrontendBucket}/*'

Outputs:
  DynamoDBTable:
    Description: 'DynamoDB Table Name'
    Value: !Ref FitnessWorkoutsTable
  
  S3BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref FrontendBucket
  
  WebsiteURL:
    Description: 'Website URL'
    Value: !GetAtt FrontendBucket.WebsiteURL